asolda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^project/', include('imagens.urls')),
    url(r'^', include('user.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

imagens/urls.py
from django.conf.urls import url
from django.conf import settings

from . import views

from .views import (
    ProjectList,
    ProjectDetail,
    ProjectCreation,
    ProjectUpdate,
    ProjectDelete,

    ImageList,
    ImageDetail,
    ImageCreation,
    ImageUpdate,
    ImageDelete
)
urlpatterns = [

    # project
    url(r'^$', ProjectList.as_view(), name='project-list'),
    url(r'^new$', ProjectCreation.as_view(), name='project-new'),
    url(r'^(?P<slug>[\w-]+)$', ProjectDetail.as_view(), name='project-detail'),
    url(r'^edit/(?P<slug>[\w-]+)$',
        ProjectUpdate.as_view(),
        name='project-edit'),
    url(r'^delete/(?P<slug>[\w-]+)$',
        ProjectDelete.as_view(),
        name='project-delete'),

    # image
    url(r'^(?P<slug_proy>[\w-]+)/images$',
        ImageList.as_view(), name='image-list'),
    url(r'^(?P<slug_proy>[\w-]+)/image/new$',
        ImageCreation.as_view(), name='image-new'),
    url(r'^(?P<slug_proy>[\w-]+)/image/(?P<slug>[\w-]+)$',
        ImageDetail.as_view(), name='image-detail'),
    url(r'^(?P<slug_proy>[\w-]+)/image/edit/(?P<slug>[\w-]+)$',
        ImageUpdate.as_view(), name='image-edit'),
    url(r'^(?P<slug_proy>[\w-]+)/image/delete/(?P<slug>[\w-]+)$',
        ImageDelete.as_view(), name='image-delete'),
    url(r'^(?P<slug_proy>[\w-]+)/image/analisys/(?P<slug>[\w-]+)$',
        ImageDetail.as_view(), name='image-analisys'),

    # media    
    # url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

]

user/urls.py
from django.conf.urls import url

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [

    # user
    url(r'^', auth_views.login, {'template_name': 'login2.html'}, name='login'),
    # url(r'^perfil/$', auth_views.perfil, {'template_name': 'perfil.html'}, name='perfil'),
    url(r'^logout/', views.my_logout, name='logout'),
    # url(r'^$', views.homelogin(), name='url_login'),
    # url(r'^login$', views.userlogin(), name='perfil')
]

imagens/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from autoslug import AutoSlugField

# Create your models here.
# from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator
from user.models import CustomUser

# class CustomUser(User):
#     username_validator = ASCIIUsernameValidator()

#     class Meta:
#         proxy = True  # If no new field is added.
#         # project = models.OneToManyField('Project')


# '''
#    clase que define los proyectos para el procesamiento de las
#    imagenes de la solda
# '''


class Project(models.Model):
    date_ini = models.DateField(auto_now_add=True)
    date_end = models.DateField(null=True)
    num_phase = models.PositiveSmallIntegerField(default=1)

    # lider = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name', unique_with='date_ini')
    description = models.TextField(null=True)

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    # images = models.OneToManyField('Image')
    # phases = models.OneToManyField('Phase')


class Image(models.Model):
    date_upload = models.DateField(auto_now_add=True)
    name = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='name', unique_with='date_upload')
    img = models.ImageField(upload_to='images/')
    phase = models.FloatField(default=0)
    # coord_right = models.FloatField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    img_diseno = models.CharField(max_length=200, null=True)
    img_bordes = models.CharField(max_length=200, null=True)
    img_values = models.CharField(max_length=200, null=True)

    bool_depth = models.BooleanField(default=False)
    bool_high = models.BooleanField(default=False)
    bool_width = models.BooleanField(default=False)


class Parameter(models.Model):
    variable = models.CharField(max_length=200)
    type_variable = models.CharField(max_length=200)
    value = models.CharField(max_length=200)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)

user/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from autoslug import AutoSlugField

# Create your models here.
from django.contrib.auth.models import User
from django.contrib.auth.validators import ASCIIUsernameValidator


class CustomUser(User):
    username_validator = ASCIIUsernameValidator()

    class Meta:
        proxy = True  # If no new field is added.
        # project = models.OneToManyField('Project')

imagens/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.core.urlresolvers import reverse_lazy, reverse

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Project, Image, Parameter

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
###########
# Project

# @method_decorator(login_required, name='dispatch')
class ProjectList(LoginRequiredMixin, ListView):
    model = Project
    def get_context_data(self, **kwargs):
        context = super(ProjectList, self).get_context_data(**kwargs)
        context['projects'] = Project.objects.filter(user = self.request.user)
        return context


class ProjectDetail(LoginRequiredMixin, DetailView):
    model = Project


class ProjectCreation(LoginRequiredMixin, CreateView):
    model = Project
    success_url = reverse_lazy('project-list')
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ProjectCreation, self).form_valid(form)


class ProjectUpdate(LoginRequiredMixin, UpdateView):
    model = Project
    success_url = reverse_lazy('project-list')
    fields = ['name', 'description']


class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('project-list')

###########
# Image


class ImageList(LoginRequiredMixin, ListView):
    model = Image


class ImageDetail(LoginRequiredMixin, DetailView):
    model = Image
    # parameter = Parameter.objects.filter(image_id=Image.id).all()
    # def get_success_url(self):
    #     return reverse('project-detail', args=[self.kwargs.get('slug_proy')])
    def get_context_data(self, **kwargs):
        context = super(ImageDetail, self).get_context_data(**kwargs)
        context['parameters'] = Parameter.objects.all()
        return context


class ImageCreation(LoginRequiredMixin, CreateView):
    model = Image
    fields = ['name', 'img']

    def form_valid(self, form):
        form.instance.project = Project.objects.get(
            slug=self.kwargs.get('slug_proy'))
        return super(ImageCreation, self).form_valid(form)

    def get_success_url(self):
        return reverse('project-detail', args=[self.kwargs.get('slug_proy')])


class ImageUpdate(LoginRequiredMixin, UpdateView):
    model = Image
    # success_url = reverse_lazy('image-list')
    fields = ['name', 'img']

    def get_success_url(self):
        return reverse('project-detail', args=[self.kwargs.get('slug_proy')])


class ImageDelete(LoginRequiredMixin, DeleteView):
    model = Image
    # success_url = reverse_lazy('image-list')

    def get_success_url(self):
        return reverse('project-detail', args=[self.kwargs.get('slug_proy')])

user/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.contrib.auth import logout

###########
# User


def my_logout(request):
    logout(request)
    return render(request,'login')

imagens/templates/imagens/default.html
 
{% extends '../base.html' %}
{% block side-bar-menu %}
<li>
    <a href="javascript:;">
        <i class="icon-briefcase"></i>
        <span class="title">Projects</span>
        <span class="arrow "></span>
    </a>
    <ul class="sub-menu">
        {% for proy in request.user.project_set.all %}
        <li>
            <a href="{% url "project-detail" proy.slug %}">
            {{proy.name}}</a>
            
        </li>
        {% endfor %}
    </ul>
</li>
{% endblock side-bar-menu %}
{% block user-log %}
                <li class="dropdown dropdown-user">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <span class="username username-hide-on-mobile">
                    {{request.user.username}} </span>
                    <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <!-- <li>
                            <a href="extra_profile.html">
                            <i class="icon-user"></i> My Profile </a>
                        </li>
                        <li>
                            <a href="page_calendar.html">
                            <i class="icon-calendar"></i> My Calendar </a>
                        </li>
                        <li>
                            <a href="inbox.html">
                            <i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
                            3 </span>
                            </a>
                        </li>
                        <li>
                            <a href="page_todo.html">
                            <i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
                            7 </span>
                            </a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="extra_lock.html">
                            <i class="icon-lock"></i> Lock Screen </a>
                        </li> -->
                        <li>
                            <a href="{% url "logout" %}">
                            <i class="icon-key"></i> Log Out </a>
                        </li>
                    </ul>
                </li>
                {% endblock user-log %}
{% block content %}
{% endblock content %}

{% block text_footer %}
         2017 &copy; rtm.      
{% endblock text_footer %}

imagens/templates/imagens/image_confirm_delete.html
{% extends 'imagens/default.html' %}
{% block title %}Project delete{% endblock title %}
{% block text_h1 %}
                {{ object.name }}
    {% endblock text_h1 %}
    {% block path_site %}
        <li>
            <i class="fa fa-home"></i>
             <a href="{% url 'project-list' %}">Projects</a>
            <i class="fa fa-angle-right"></i>
        </li>
         <li>
            <a href="{% url "project-detail" object.project.slug %}">{{object.project.name}}</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{% url "image-detail" object.project.slug object.slug %}">{{ object.name }}</a>
        </li>
    {% endblock path_site %}
{% block content %}

<form method="post">{% csrf_token %}
    ¿Do you want really delete "{{ object.name }}"?
    <input class="btn red" type="submit" value="Submit" />
</form>

{% endblock content %}

imagens/templates/imagens/image_form.html
{% extends 'imagens/default.html' %}
{% block title %}Image form{% endblock title %}
{% block text_h1 %}
                {{ image.name }}
    {% endblock text_h1 %}
    {% block path_site %}
       
    {% endblock path_site %}
{% block content %}

<div class="portlet box blue">
									<div class="portlet-title">
										<div class="caption">
											<i class="fa fa-gift"></i>Welding-bead image form
										</div>
										<!-- <div class="tools">
											<a href="javascript:;" class="collapse" data-original-title="" title="">
											</a>
											<a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
											</a>
											<a href="javascript:;" class="reload" data-original-title="" title="">
											</a>
											<a href="javascript:;" class="remove" data-original-title="" title="">
											</a>
										</div> -->
									</div>
									<div class="portlet-body form">
										<!-- BEGIN FORM-->
										{% load mytags %}
										<form method="post" enctype="multipart/form-data" class="form-horizontal form-row-seperated">
											{% csrf_token %}
											<div class="form-body">
												<div class="form-group">
													<label class="control-label col-md-3">Name
														<span class="required" aria-required="true">
														* </span>
													</label>
													<div class="col-md-9">
														{{ form.name|addcss:"form-control" }}
														<!-- <input type="text" placeholder="Image name" data-required="1" class="form-control"> -->
														<span class="help-block">
														Image name</span>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">Upload</label>
													<div class="col-md-9">
														{{ form.img|addcss:"form-control" }}
														<!-- <input type="textarea" placeholder="Image description" class="form-control"> -->
														<span class="help-block">
														Image upload </span>
													</div>
												</div>
											</div>	
											<div class="form-actions">
												<div class="row">
													<div class="col-md-offset-3 col-md-9">
														<button type="submit" class="btn green"><i class="fa fa-pencil"></i> Submit</button>
														<button type="button" class="btn default">Cancel</button>
													</div>
												</div>
											</div>
										</form>
										<!-- END FORM-->
									</div>
								</div>

{% endblock content %}

imagens/templates/imagens/image_list.html
<p>
    <a href="{% url "image-new" %}">Agregar curso</a>
</p>

<ul>
    {% for image in image_list %}
        <li>
            <p>{{ image.name }}</p>
            <p>
                <a href="{% url "image-detail" image.slug %}">Ver</a> | 
                <a href="{% url "image-edit" image.slug %}">Editar</a> | 
                <a href="{% url "image-delete" image.slug %}">Borrar</a> 
            </p>
        </li>
    {% endfor %}
</ul>

imagens/templates/imagens/project_confirm_delete.html
{% extends 'imagens/default.html' %}
{% block title %}Project delete{% endblock title %}
{% block text_h1 %}
                {{ object.name }}
    {% endblock text_h1 %}
    {% block path_site %}
        <li>
            <i class="fa fa-home"></i>
             <a href="{% url 'project-list' %}">Projects</a>
            <i class="fa fa-angle-right"></i>
        </li>
         <li>
            <a href="{% url "project-detail" object.slug %}">{{object.name}}</a>
        </li>
    {% endblock path_site %}
{% block content %}

<form method="post">{% csrf_token %}
    ¿Do you want really delete "{{ object.name }}"?
    <input class="btn red" type="submit" value="Submit" />
</form>

{% endblock content %}

imagens/templates/imagens/project_detail.html
{% extends 'imagens/default.html' %}
{% block title %}Project details{% endblock title %}

{% block text_h1 %}
                {{ project.name }}
    {% endblock text_h1 %}
    {% block path_site %}
         <li>
            <i class="fa fa-home"></i>
             <a href="{% url 'project-list' %}">Projects</a>
            <i class="fa fa-angle-right"></i>
        </li><li>
            <a href="#">{{ project.name }}</a>
        </li> 
    {% endblock path_site %}

{% block content %}

<p>Start date: <i>{{ project.date_ini }}</i></p>
<p>description: <i>{{ project.description }}</i></p>
<!-- <p>
    <a href="{% url "project-list" %}">Regresar</a>
</p> -->
        <div class="portlet box grey-cascade">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-cogs"></i>Welding-bead image
                            </div>
                            <div class="tools">
                                <div class="btn-group">                                    
                                <a class="btn green" href="{% url "image-new" project.slug %}">Add image
                                <i class="fa fa-plus"></i>
                                </a>
                                </div>
                               <!--  <a href="javascript:;" class="collapse" data-original-title="" title="">
                               </a>
                               <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
                               </a>
                               <a href="javascript:;" class="reload" data-original-title="" title="">
                               </a>
                               <a href="javascript:;" class="remove" data-original-title="" title="">
                               </a> -->
                            </div>
                        </div>
                        <div class="portlet-body flip-scroll">
                            <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="flip-content">
                            <tr>
                                <th width="20%">
                                     Name
                                </th>
                                <th class="numeric">
                                     Upload date
                                </th>
                                <th class="numeric">
                                     State
                                </th>
                                <th >
                                     Actions
                                </th>                                
                            </tr>
                            </thead>
                            <tbody>
                         {% for img in project.image_set.all %}       
                            <tr>
                                <td>
                                     {{ img.name }}
                                </td>
                                <td class="numeric">
                                     {{ img.date_upload }}
                                </td>
                                <td class="numeric">
                                     {% if img.phase == 3.0 %}
                                        Values detection
                                      {% elif img.phase == 2.0 %}
                                        Edge detection
                                      {% elif img.phase == 1.0 %}
                                        Coord detection
                                      {% else %}
                                        Start
                                     {% endif %} 
                                </td>  
                                <td>
                                     <!-- <a class="btn green" href="{% url "image-detail" project.slug img.slug %}">Detail</a>  -->
                                    <a class="btn green" href="{% url "image-edit" project.slug img.slug %}">
                                        <i class="fa fa-pencil"></i>
                                    Edit</a> 
                                    <a class="btn red" href="{% url "image-delete" project.slug img.slug %}">
                                        <i class="fa fa-trash-o"></i>
                                        delete</a>
                                    <a class="btn green" href="{% url "image-analisys" project.slug img.slug %}">
                                        <i class="fa fa-gear"></i>
                                        Analisys</a> 
                                </td>                               
                            </tr>
                            {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    </div>

{% endblock content %}

imagens/templates/imagens/project_form.html
{% extends 'imagens/default.html' %}
{% block title %}Project form{% endblock title %}
{% block text_h1 %}
                {{ project.name }}
    {% endblock text_h1 %}
    {% block path_site %}
         <li>
            <i class="fa fa-home"></i>
             <a href="{% url 'project-list' %}">Projects</a>
            <i class="fa fa-angle-right"></i>
        </li><li>
            <a href="#">{{ project.name }}</a>
        </li> 
    {% endblock path_site %}
{% block content %}

<div class="portlet box green">
									<div class="portlet-title">
										<div class="caption">
											<i class="fa fa-gift"></i>Project form
										</div>
										<!-- <div class="tools">
											<a href="javascript:;" class="collapse" data-original-title="" title="">
											</a>
											<a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
											</a>
											<a href="javascript:;" class="reload" data-original-title="" title="">
											</a>
											<a href="javascript:;" class="remove" data-original-title="" title="">
											</a>
										</div> -->
									</div>
									<div class="portlet-body form">
										<!-- BEGIN FORM-->
										{% load mytags %}
										<form method="post" class="form-horizontal form-row-seperated">
											{% csrf_token %}
											<div class="form-body">
												<div class="form-group">
													<label class="control-label col-md-3">Name
														<span class="required" aria-required="true">
														* </span>
													</label>
													<div class="col-md-9">
														{{ form.name|addcss:"form-control" }}
														<!-- <input type="text" placeholder="Project name" data-required="1" class="form-control"> -->
														<span class="help-block">
														Project name </span>
													</div>
												</div>
												<div class="form-group">
													<label class="control-label col-md-3">Description</label>
													<div class="col-md-9">
														{{ form.description|addcss:"form-control" }}
														<!-- <input type="textarea" placeholder="Project description" class="form-control"> -->
														<span class="help-block">
														Project description</span>
													</div>
												</div>
											</div>	
											<div class="form-actions">
												<div class="row">
													<div class="col-md-offset-3 col-md-9">
														<button type="submit" class="btn green"><i class="fa fa-pencil"></i> Submit</button>
														<button type="button" class="btn default">Cancel</button>
													</div>
												</div>
											</div>
										</form>
										<!-- END FORM-->
									</div>
								</div>



{% endblock content %}

imagens/templates/imagens/project_list.html
{% extends 'imagens/default.html' %}
{% block title %}Projects{% endblock title %}

    {% block text_h1 %}
                Projects <!-- <small>reports & statistics</small> -->
    {% endblock text_h1 %}
    {% block path_site %}
        <!-- <li>
            <i class="fa fa-home"></i>
             <a href="{% url 'project-list' %}">Projects</a>
            <i class="fa fa-angle-right"></i>
        </li><li>
            <a href="#">Dashboard</a>
        </li> -->
    {% endblock path_site %}
{% block content %}
<div class="portlet box grey-cascade">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-cogs"></i>Projects
                            </div>
                            <div class="tools">
                                <div class="btn-group">                                    
                                <a class="btn green" href="{% url "project-new" %}">Add Project
                                <i class="fa fa-plus"></i>
                                </a>
                                </div>
                               <!--  <a href="javascript:;" class="collapse" data-original-title="" title="">
                               </a>
                               <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
                               </a>
                               <a href="javascript:;" class="reload" data-original-title="" title="">
                               </a>
                               <a href="javascript:;" class="remove" data-original-title="" title="">
                               </a> -->
                            </div>
                        </div>
                        <div class="portlet-body flip-scroll">
                            <table class="table table-bordered table-striped table-condensed flip-content">
                            <thead class="flip-content">
                            <tr>
                                <th width="20%">
                                     Name
                                </th>
                                <th>
                                     Description
                                </th>
                                <th class="numeric">
                                     Pieces
                                </th>
                                <th class="numeric">
                                     Start date
                                </th>
                                <th >
                                     Actions
                                </th>                                
                            </tr>
                            </thead>
                            <tbody>
                         {% for project in projects %}       
                            <tr>
                                <td>
                                     {{ project.name }}
                                </td>
                                <td>
                                     {{ project.description }}
                                </td>
                                <td class="numeric">
                                    {{ project.image_set.all|length }}
                                </td>
                                <td class="numeric">
                                     {{ project.date_ini }}
                                </td>
                                <td>
                                     <a class="btn green" href="{% url "project-detail" project.slug %}">Detail</a> 
                                    <a class="btn green" href="{% url "project-edit" project.slug %}">
                                        <i class="fa fa-pencil"></i>
                                    Edit</a> 
                                    <a class="btn red" href="{% url "project-delete" project.slug %}">
                                        <i class="fa fa-trash-o"></i>
                                        delete</a>
                                    <a class="btn green" href="{% url "image-new" project.slug %}">
                                        <i class="fa fa-plus"></i>
                                        Add imagen</a> 
                                </td>                               
                            </tr>
                            {% endfor %}
                            </tbody>
                            </table>
                        </div>
                    </div>

{% endblock content %}

user/templates/login.html
{% extends 'imagens/default.html' %}
{% block head_css_page %}
<style type="text/css">
    .page-bar, body {
        background-color: #fff !important;
    }
</style>
{% endblock head_css_page %}
{% block user-log %}
{% endblock user-log %}
{% block text_h3 %}
    {% endblock text_h3 %}
    {% block path_site %}
    {% endblock path_site %}

{% block sidebar %}
{% endblock sidebar %}
{% block content %}
<div class="center">    
<h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    {{request.user.email}}
  </form>
</div>
{% endblock content %}